### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by yywangvr** [neuropsychology/NeuroKit#395] opened 2020-12-14 10:10 UTC
Hello, I get the following warning:

lib/python3.7/site-packages/neurokit2/eda/eda_findpeaks.py:289: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  scrs = np.array(scrs)

Maybe a slight correction is required.  Thank you.

**Comment by DominiqueMakowski** [comment] 2021-03-11 14:30
@Tam-Pham is there any update on this?

**Comment by JanCBrammer** [comment] 2021-03-15 18:44
duplicate of #421.

**Closed by JanCBrammer** 2021-03-15 18:44 UTC
