### ISSUE TITLE
nk.ecg_delineate do not show Q and S peaks.

### ISSUE THREAD

**Issue by HelenaRoMar** [neuropsychology/NeuroKit#480] opened 2021-07-14 07:06 UTC
Hello!!

I was experimenting with the characteristics of Neurokit2 and doing the examples I have some problem with the ecg_delineate feature.
I used:

# Delineate the ECG signal
_, waves_peak = nk.ecg_delineate(ecg_signal, rpeaks, sampling_rate=fs)

I followed this[ example](https://neurokit2.readthedocs.io/en/latest/examples/ecg_delineate.html)

So I don't understand why only T and P peaks appear.

Thank you in advande for your help.

**Comment by zen-juen** [comment] 2021-07-17 05:28
Hi @HelenaRoMar if you didn't use one of neurokit's example dataset for this, can you share with us a sample of your data and a reproducible script so that we can investigate the error?

**Comment by feliperbroering** [comment] 2021-07-19 02:26
Hello, I observed the same problem, I tested with my samples and also with the neurokit dataset.

The S and Q peaks are always missing.

![image](https://user-images.githubusercontent.com/6460296/126094043-2a3fefb2-39d4-49ed-89f9-9d3e10b90d52.png)

**Comment by Tam-Pham** [comment] 2021-07-19 07:46
Hi  @HelenaRoMar and @feliperbroering 

Thank you for checking in with us. Please note that this behaviour is expected at the current stage of the function. As described [here](https://neurokit2.readthedocs.io/en/latest/functions.html#neurokit2.ecg.ecg_delineate), the current default method in `ecg_delineate()` is `discrete wavelet method (dwt)` and it only returns the following: P-peaks, T-peaks, P-onsets, P-offsets, T-onsets, T-offsets, QRS-onsets and QRS-offsets .

The only one method that support the return of Q-peak and S-peak is the derivative method (`method="peak`). We do hope to further improve the wavelet methods to be able to return these peaks information soon. But for now, for these 2 peaks, please run the delineate function but change the method to `peak` instead of `dwt`.

**Comment by HelenaRoMar** [comment] 2021-07-19 08:16
Hi @Tam-Pham 

Thank you so much for your response. 

It was a confusion when I read in the documentation:  _‘peak’ (default)_ 
![image](https://user-images.githubusercontent.com/87412801/126125191-78197c5f-e7ec-4f3b-88ea-b8941d059a3e.png)

But using:  _method="peak"_
```
ecg = nk.ecg_simulate(duration=10, sampling_rate=1000)
cleaned = nk.ecg_clean(ecg, sampling_rate=1000)
_, rpeaks = nk.ecg_peaks(cleaned, sampling_rate=1000)
signals, waves = nk.ecg_delineate(cleaned, rpeaks, sampling_rate=1000, method="peak", show=True)
```

It works perfectly:
![image](https://user-images.githubusercontent.com/87412801/126126320-69f95ae6-45b1-4cab-b3d6-b53c582e51a0.png)

**Comment by feliperbroering** [comment] 2021-07-19 14:23
Hello @Tam-Pham and @HelenaRoMar 

Thanks for your feedback! 

I think is just a doc issue, because the 0.1.0 version works exactly as described in the example:
https://neurokit2.readthedocs.io/en/latest/examples/ecg_delineate.html

With the 0.1.2 version you must to explicitly use `method="peak` to works.


In 0.1.2 version:
![image](https://user-images.githubusercontent.com/6460296/126173912-8269aa7f-b83b-411c-b778-e53552aa5246.png)


In the 0.1.0 version:
![image](https://user-images.githubusercontent.com/6460296/126174809-7f313a05-cfbb-4cb9-92bf-f9e7c9eea5e2.png)


In the 0.1.2 version forcing "method="peak":
![image](https://user-images.githubusercontent.com/6460296/126175094-740f9933-fc1c-497e-9764-eada4cdc6fbb.png)

**Comment by Tam-Pham** [comment] 2021-07-22 07:31
We indeed have only recently changed the default method in `ecg_delineate()` from "peak" to "dwt". It's strange that the documentation is not yet updated. I will check again. Thanks for letting us know! 

I will close this issue as of now :)

**Closed by Tam-Pham** 2021-07-22 07:31 UTC

**Comment by chepo92** [comment] 2021-07-25 00:09
Same issue with the default notebook example, I get ` KeyError: 'ECG_Q_Peaks' ` thanks for the clarification on the method to use. Also I think the readthedocs automation is may not be working https://github.com/neuropsychology/NeuroKit/blob/master/docs/examples/ecg_delineate.ipynb
