### ISSUE TITLE
Heart/respiration rate - interpolated signal creates crazy values (including negative values)

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#242] opened 2020-06-06 07:49 UTC
Follow-up of #236 @Mitchellb16

So I took a look at your data and it seems that indeed the cubic interpolation (used by default) extends the range. It seems like the more there is short and sudden variability, and the more it will struggle to connect the dots with curves, resulting positives and negative spikes between close peaks.

![image](https://user-images.githubusercontent.com/8875533/83938940-66248f00-a80b-11ea-8f9d-42b22aa13570.png)

Here's the difference between linear, quadratic (2nd order) and cubic (3rd order) interpolation. As we can see, the cubic one extends the range drastically it some cases, resulting in implausible values (negative numbers).

We had this discussion in #180, with the suggestion of changing the default interpolation method to linear which has the advantage of being "safe", although not realistic. My guess is that cubic interpolation should work fine in most cases **but** in regions with sudden, high and chaotic variability, which is usually indicative of artefacts.

Given that, you could either

- Switch to linear interpolation (`nk.rsp_rate(peaks, interpolation_order="linear")`)
- Remove the peak locations or intervals that are likely to be artefacted

Hope that helps

**Comment by JanCBrammer** [comment] 2020-06-06 08:56
Closing this since it's a duplicate of, and referenced in #243

**Closed by JanCBrammer** 2020-06-06 08:56 UTC
Labels: ECG :heart:, RSP :triumph:, signal processing :chart_with_upwards_trend:
